name: Sync to Azure DevOps

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Mirror to Azure DevOps
      env:
        AZURE_REPO_URL: https://jeremydumais.visualstudio.com/CPP-DateTime-Library/_git/CPP-DateTime-Library
        AZURE_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        git config --global user.email "jeremydumais@hotmail.com"
        git config --global user.name "Jeremy Dumais"

        git remote add azure https://jeremydumais:${AZURE_PAT}@jeremydumais.visualstudio.com/CPP-DateTime-Library/_git/CPP-DateTime-Library
        git push --mirror azure
